2025-01-16T16:19:39.592044+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2025-01-16T16:19:39.593023+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2025-01-16T16:19:39.593102+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "ghcr.io/ansible/community-ansible-dev-tools:latest": failed to find image ghcr.io/ansible/community-ansible-dev-tools:latest: ghcr.io/ansible/community-ansible-dev-tools:latest: image not known

2025-01-16T16:20:17.804026+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-16T16:20:17.807540+00:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was: Traceback (most recent call last):
  File "/Users/aroque/.cache/ansible-navigator/image_introspect.py", line 16, in <module>
    from typing import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib64/python3.9/typing.py)
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-16T16:20:28.787515+00:00 CRITICAL 'ansible_navigator.actions._actions.run_interactive' Subcommand 'select' encountered a fatal error.
2025-01-16T16:20:28.788055+00:00 ERROR 'ansible_navigator.actions._actions.run_interactive' Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/_actions.py", line 172, in run_interactive
    return run_action(app=app, interaction=interaction)
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/select.py", line 41, in run
    app.steps.append(app.steps.current.select_func())  # add next
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 320, in _build_image_content
    value=self._images.selected["ansible"],
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'ansible'
2025-01-16T16:20:41.025403+00:00 CRITICAL 'ansible_navigator.actions._actions.run_interactive' Subcommand 'select' encountered a fatal error.
2025-01-16T16:20:41.026002+00:00 ERROR 'ansible_navigator.actions._actions.run_interactive' Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/_actions.py", line 172, in run_interactive
    return run_action(app=app, interaction=interaction)
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/select.py", line 41, in run
    app.steps.append(app.steps.current.select_func())  # add next
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 330, in _build_image_content
    self._images.selected["python"]["details"],
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'python'
2025-01-16T16:20:53.128529+00:00 CRITICAL 'ansible_navigator.actions._actions.run_interactive' Subcommand 'select' encountered a fatal error.
2025-01-16T16:20:53.128901+00:00 ERROR 'ansible_navigator.actions._actions.run_interactive' Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/_actions.py", line 172, in run_interactive
    return run_action(app=app, interaction=interaction)
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/select.py", line 41, in run
    app.steps.append(app.steps.current.select_func())  # add next
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 320, in _build_image_content
    value=self._images.selected["ansible"],
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'ansible'
2025-01-16T16:22:43.659174+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-16T16:22:43.662314+00:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was: Traceback (most recent call last):
  File "/Users/aroque/.cache/ansible-navigator/image_introspect.py", line 16, in <module>
    from typing import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib64/python3.9/typing.py)
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-16T16:22:55.450731+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-16T16:22:55.452063+00:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was: Traceback (most recent call last):
  File "/Users/aroque/.cache/ansible-navigator/image_introspect.py", line 16, in <module>
    from typing import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib64/python3.9/typing.py)
Traceback (most recent call last):
  File "/Users/aroque/.local/pipx/venvs/ansible-navigator/lib/python3.13/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
